In [1]:
!pip install -q pandas_datareader

In [2]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt 
from pandas_datareader import wb

In [3]:
codigos = ["NE.EXP.GNFS.CD", "NE.IMP.GNFS.CD", "NV.AGR.TOTL.CD", "NY.GDP.MKTP.CD", "NE.RSB.GNFS.CD"]

In [5]:
dados = wb.download(country="all", indicator=codigos, start = 2019, end = 2019).reset_index()

C:\Users\Familia dos Bertelis\AppData\Local\Temp\ipykernel_13876\203588680.py:1: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  dados = wb.download(country="all", indicator=codigos, start = 2019, end = 2019).reset_index()

In [15]:
dados.head(10)

,country,year,NE.EXP.GNFS.CD,NE.IMP.GNFS.CD,NV.AGR.TOTL.CD,NY.GDP.MKTP.CD,NE.RSB.GNFS.CD
0,Afghanistan,2019,NaN,NaN,4.845363e+09,1.879944e+10,NaN
1,Africa Eastern and Southern,2019,2.455958e+11,2.799227e+11,1.319619e+11,1.018715e+12,NaN
2,Africa Western and Central,2019,NaN,NaN,2.409897e+11,1.026996e+12,NaN
3,Albania,2019,4.821429e+09,6.926960e+09,2.830318e+09,1.558511e+10,-2.105530e+09
4,Algeria,2019,3.948114e+10,5.049085e+10,2.220758e+10,1.934597e+11,-1.100971e+10
5,American Samoa,2019,3.990000e+08,6.140000e+08,NaN,6.470000e+08,-2.150000e+08
6,Andorra,2019,NaN,NaN,1.648986e+07,3.155150e+09,NaN
7,Angola,2019,3.000118e+10,1.901659e+10,1.000393e+10,8.073443e+10,1.098460e+10
8,Antigua and Barbuda,2019,1.194093e+09,1.180426e+09,2.842963e+07,1.726448e+09,1.366667e+07
9,Arab World,2019,1.250081e+12,1.100322e+12,1.420770e+11,2.965286e+12,NaN

In [9]:
paises = wb.get_countries()

In [10]:
paises2 = paises[paises != "Aggregates"].name

In [11]:
paises2

0                                                  Aruba
1                            Africa Eastern and Southern
2                                            Afghanistan
3                                                 Africa
4                             Africa Western and Central
                             ...
291    Sub-Saharan Africa excluding South Africa and ...
292                                          Yemen, Rep.
293                                         South Africa
294                                               Zambia
295                                             Zimbabwe
Name: name, Length: 296, dtype: object

In [12]:
dados2 = dados[dados["country"].isin(paises2)].dropna()

In [17]:
dados2

,country,year,NE.EXP.GNFS.CD,NE.IMP.GNFS.CD,NV.AGR.TOTL.CD,NY.GDP.MKTP.CD,NE.RSB.GNFS.CD
3,Albania,2019,4.821429e+09,6.926960e+09,2.830318e+09,1.558511e+10,-2.105530e+09
4,Algeria,2019,3.948114e+10,5.049085e+10,2.220758e+10,1.934597e+11,-1.100971e+10
7,Angola,2019,3.000118e+10,1.901659e+10,1.000393e+10,8.073443e+10,1.098460e+10
8,Antigua and Barbuda,2019,1.194093e+09,1.180426e+09,2.842963e+07,1.726448e+09,1.366667e+07
10,Argentina,2019,8.025948e+10,6.584562e+10,2.381408e+10,4.477547e+11,1.441386e+10
...,...,...,...,...,...,...,...
257,Vanuatu,2019,4.714967e+08,4.592509e+08,1.977992e+08,9.365263e+08,1.224588e+07
259,Viet Nam,2019,2.847374e+11,2.659763e+11,3.940337e+10,3.343653e+11,1.876110e+10
261,West Bank and Gaza,2019,2.659300e+09,9.161700e+09,1.208600e+09,1.713350e+10,-6.502400e+09
264,Zambia,2019,8.073235e+09,7.961078e+09,6.668085e+08,2.330867e+10,1.121567e+08
265,Zimbabwe,2019,7.595269e+09,7.784812e+09,7.574082e+09,3.335770e+10,-1.895436e+08

In [21]:
#Construindo array com os países

vetor = {}

for rowid, row in dados2.iterrows():
    vetor[row["country"]] = row[codigos].values

In [19]:
vetor

{'Albania': array([4821429218.47484, 6926959712.72243, 2830318199.77187,
        15585111614.0376, -2105530494.24759], dtype=object),
 'Algeria': array([39481135535.1468, 50490845023.6565, 22207582617.6879,
        193459662090.677, -11009709488.5098], dtype=object),
 'Angola': array([30001180996.3857, 19016585500.3641, 10003931065.3174,
        80734428592.5368, 10984595496.0216], dtype=object),
 'Antigua and Barbuda': array([1194092592.59259, 1180425925.92593, 28429629.6296296,
        1726448148.14815, 13666666.6666667], dtype=object),
 'Argentina': array([80259482469.139, 65845624691.108, 23814083576.0785,
        447754683615.225, 14413857778.0311], dtype=object),
 'Armenia': array([5755867284.48234, 7570200592.04305, 1569706412.82118,
        13619290539.2116, -1814333307.56071], dtype=object),
 'Aruba': array([2232926815.64246, 2384139106.14525, 616592.72441857,
        3346623191.45988, -151212290.502794], dtype=object),
 'Australia': array([336477593836.115, 306786753625.531, 29704429023.1289,
        1398349602956.35, 29690840210.5837], dtype=object),
 'Austria': array([247609283522.368, 231731288458.933, 4627558347.48235,
        442983642371.842, 15877995063.4353], dtype=object),
 'Azerbaijan': array([23629764705.8824, 17712470588.2353, 2743705882.35294,
        48174235294.1176, 5917294117.64706], dtype=object),
 'Bahamas, The': array([4644400000.0, 4488400000.0, 71000000.0, 13277000000.0, 156000000.0],
       dtype=object),
 'Bahrain': array([29564361702.1277, 25207712765.9574, 108670212.765957,
        40446808510.6383, 4356648936.17021], dtype=object),
 'Bangladesh': array([45992932855.1263, 64919190426.113, 42061125594.3548,
        351231654603.692, -18926257570.9868], dtype=object),
 'Belarus': array([41927532636.0335, 42353437235.1243, 4376457787.44736,
        64410170653.4569, -425904599.090823], dtype=object),
 'Belgium': array([445308040880.784, 442788775443.921, 3857933055.68627,
        536726344405.489, 2519265436.86274], dtype=object),
 'Belize': array([1238668200.0, 1200664850.0, 156112850.0, 2381187850.0, 38003350.0],
       dtype=object),
 'Benin': array([4264332526.72108, 4900485060.17756, 3867881064.21888,
        14391686313.4641, -636152533.456475], dtype=object),
 'Bermuda': array([3841155000.0, 1916492000.0, 16403000.0, 7423465000.0, 1924663000.0],
       dtype=object),
 'Bhutan': array([860577748.409369, 1221920791.32363, 353832021.347355,
        2735683570.46155, -361343042.914263], dtype=object),
 'Bolivia': array([9834601157.7424, 12643630390.7381, 3744436034.73227,
        49056643589.0014, -2809029232.99566], dtype=object),
 'Bosnia and Herzegovina': array([8201250825.66056, 11158117516.8252, 1116310702.50692,
        20482608984.3316, -2956866691.1646], dtype=object),
 'Botswana': array([6203274315.31089, 7694781424.87258, 348472503.42534,
        16725908148.5481, -1491507109.56169], dtype=object),
 'Brazil': array([264562972885.655, 276634806846.042, 78772031121.1664,
        1873288158838.63, -12071833960.3867], dtype=object),
 'Brunei Darussalam': array([7804888584.60408, 6810532693.06468, 132814086.301393,
        13469235364.7032, 994355891.539408], dtype=object),
 'Bulgaria': array([44050873991.5812, 41762196901.9634, 2193655905.23868,
        68507731353.9114, 2288677089.61777], dtype=object),
 'Burkina Faso': array([4690831780.11539, 4994381288.40906, 2921262720.82891,
        16032813503.3707, -303549508.293677], dtype=object),
 'Cabo Verde': array([1051880072.22161, 1281435256.84643, 99937226.3692216,
        2252177124.32402, -229555184.624823], dtype=object),
 'Cambodia': array([20340881132.781, 22117532079.4063, 5663671140.05318,
        36685356407.7206, -1776650946.62522], dtype=object),
 'Cameroon': array([7874085866.66636, 9333197587.66967, 6665089103.45158,
        39667757527.6578, -1459111721.00331], dtype=object),
 'Canada': array([564142104614.779, 589706748631.384, 29592400071.463,
        1743725183672.52, -25564644016.6048], dtype=object),
 'Cayman Islands': array([4127896511.58605, 2695690782.76313, 24618294.9098687,
        5941896599.57333, 1432205728.82292], dtype=object),
 'Central African Republic': array([349974468.904547, 762137823.137317, 629557507.566426,
        2221301351.43918, -412163354.23277], dtype=object),
 'Chad': array([3721677783.17558, 3235878756.21652, 5603038562.44464,
        14905517742.8454, 485799026.959065], dtype=object),
 'Chile': array([77571035535.566, 82753869493.5382, 11097485442.7441,
        278285058719.466, -5182833957.97221], dtype=object),
 'China': array([2628941104657.6, 2496153305902.9, 1020116721824.28,
        14560167101283.4, 132787798754.701], dtype=object),
 'Colombia': array([51258795210.3544, 70067176051.0406, 20708660529.0066,
        323031701192.84, -18808380840.6861], dtype=object),
 'Comoros': array([151737907.193166, 350371110.785613, 423136632.560581,
        1187915408.87243, -198633203.592447], dtype=object),
 'Congo, Dem. Rep.': array([13335027131.6524, 15200849680.4705, 6160805403.56467,
        46845900350.0332, -1865822548.81811], dtype=object),
 'Congo, Rep.': array([7854704721.17581, 4944506820.52635, 1026862418.78167,
        13976637779.9763, 2910197900.64946], dtype=object),
 'Costa Rica': array([22111572547.4852, 20249829012.3889, 2706863473.33596,
        64417670521.3545, 1861743535.09631], dtype=object),
 "Cote d'Ivoire": array([13683059068.9034, 13284189624.8842, 9472993128.39508,
        60382894697.3557, 398869444.019138], dtype=object),
 'Croatia': array([31035693351.0662, 31288345110.4722, 1756014513.19666,
        61466721186.3116, -252651759.406038], dtype=object),
 'Cuba': array([12632000000.0, 10971100000.0, 3689600000.0, 103427600000.0,
        1660900000.0], dtype=object),
 'Cyprus': array([19846298344.5206, 19581301859.6716, 457971556.383469,
        26196667099.5303, 264996484.849028], dtype=object),
 'Czechia': array([185212440994.669, 169560596975.875, 4857307939.69192,
        256794209028.77, 15651844018.7945], dtype=object),
 'Denmark': array([203616268094.231, 182858534958.076, 4287217763.41859,
        345401473012.615, 20757733136.1547], dtype=object),
 'Djibouti': array([5149667174.954, 4763668896.7539, 46930535.502276, 3088851450.30694,
        385998278.2001], dtype=object),
 'Dominican Republic': array([20793631484.4658, 24593322194.2051, 3855676746.39045,
        89146130744.723, -3799690709.73937], dtype=object),
 'Ecuador': array([25875328000.0, 25859813000.0, 8378234000.0, 107595830000.0,
        15515000.0], dtype=object),
 'Egypt, Arab Rep.': array([53041002277.9043, 78012528473.8041, 34089504555.8087,
        318678815489.749, -24971526195.8998], dtype=object),
 'El Salvador': array([8052490000.0, 12388470000.0, 1383420000.0, 26881140000.0,
        -4335980000.0], dtype=object),
 'Equatorial Guinea': array([5810566663.64454, 4971586017.96072, 277043776.953208,
        11364133549.7478, 838980645.683818], dtype=object),
 'Estonia': array([22955204325.3882, 21780286721.0117, 722147258.360783,
        31873748770.0313, 1174917604.37647], dtype=object),
 'Eswatini': array([2066646226.29074, 1933575697.79077, 342768013.012091,
        4617018958.69086, 133070528.499966], dtype=object),
 'Ethiopia': array([7291628539.24915, 19170757494.8805, 30887001320.8191,
        91834517112.628, -11879128955.6314], dtype=object),
 'Faroe Islands': array([1821680268.24413, 1726424994.45606, 556972714.529405,
        3266432734.22819, 95255273.7880667], dtype=object),
 'Finland': array([108456929458.823, 106661292345.098, 5847015364.70587,
        267014821129.411, 1795637113.72549], dtype=object),
 'France': array([895514790269.018, 913209092423.528, 38344688699.6078,
        2722793515171.76, -17694302154.5098], dtype=object),
 'French Polynesia': array([1240128736.0656, 2572340201.84497, 135530016.652573,
        6022276196.13871, -1332211465.77937], dtype=object),
 'Gabon': array([8678687831.55984, 3711865707.4978, 937277186.32249,
        16874405465.391, 4966822124.06204], dtype=object),
 'Gambia, The': array([365730558.072245, 649852994.642033, 362795314.8368,
        1813609692.49994, -284122436.569788], dtype=object),
 'Georgia': array([9578376986.37911, 11201362124.0068, 1293857796.53802,
        17638337116.9126, -1622985137.6277], dtype=object),
 'Germany': array([1676629137011.76, 1454588084839.21, 32990913803.9215,
        3959894794039.21, 222041052172.549], dtype=object),
 'Ghana': array([25597786148.2046, 26913986432.3936, 11840883313.0633,
        68352629246.1555, -1316200284.18894], dtype=object),
 'Greece': array([82010713282.0312, 85057106800.7999, 7590536462.10195,
        207305649887.019, -3046393518.76862], dtype=object),
 'Greenland': array([1230176954.70104, 1533065634.97693, 553794040.195536,
        2997309971.87623, -302888680.275891], dtype=object),
 'Guatemala': array([13591570047.3112, 21534755007.9268, 7260931505.95229,
        77172331693.4093, -7943184960.61558], dtype=object),
 'Guinea': array([4710654157.7052, 5830607791.61899, 3552582219.41925,
        13442861496.4454, -1119953633.9138], dtype=object),
 'Guinea-Bissau': array([291804550.872984, 505407400.662735, 500983765.601279,
        1596227316.34846, -213602849.789751], dtype=object),
 'Haiti': array([1585349842.81308, 5107129494.68417, 2881197991.33541,
        15016090929.5125, -3521779651.87109], dtype=object),
 'Honduras': array([10007373348.5297, 14740482898.6338, 2646979487.43497,
        24882225741.8119, -4733109550.10415], dtype=object),
 'Hong Kong SAR, China': array([645006704384.439, 639345975716.69, 262509161.340019,
        363074545072.389, 5660728667.74878], dtype=object),
 'Hungary': array([133707076997.179, 130068829560.311, 5484228996.07789,
        164936682033.992, 3638247436.86782], dtype=object),
 'Iceland': array([11172065684.1319, 9764032620.96263, 1078915398.50407,
        24985687022.0452, 1408033063.16932], dtype=object),
 'India': array([529245063167.215, 602315056052.526, 475121943129.794,
        2835606256558.19, -73069992885.3108], dtype=object),
 'Indonesia': array([208057763659.252, 213034646334.827, 142266719988.167,
        1119099871350.2, -4976882675.57574], dtype=object),
 'Iran, Islamic Rep.': array([77652596277.174, 91441131366.5632, 41090823480.9061,
        347988400957.999, -13788535089.3892], dtype=object),
 'Iraq': array([88902900000.0, 72282500000.0, 8808100169.20474, 233636097800.338,
        16620400000.0], dtype=object),
 'Ireland': array([534361678398.431, 514830799947.372, 3884379521.50588,
        407211793800.713, 19530878451.0588], dtype=object),
 'Israel': array([116111159420.199, 109553655513.763, 5394445077.90974,
        400645216358.857, 6557503906.43625], dtype=object),
 'Italy': array([625065757185.881, 560326098494.117, 36729958666.6666,
        2019606796583.53, 64739658691.7646], dtype=object),
 'Japan': array([893782209080.495, 908591904960.75, 53173266353.0172,
        5117993853016.51, -14809695880.2551], dtype=object),
 'Jordan': array([16170140845.0704, 21963521126.7606, 1945643802.8169,
        44503006338.0282, -5793380281.69014], dtype=object),
 'Kazakhstan': array([66197682052.4286, 51629140772.7225, 8113866801.27454,
        181667184854.501, 14568541279.7061], dtype=object),
 'Kenya': array([11471243360.3894, 20408407783.966, 20940110008.2087,
        100378436207.371, -8937164423.57661], dtype=object),
 'Kiribati': array([32509629.5463649, 180817476.661092, 58539071.445019,
        216985388.322754, -148307847.114727], dtype=object),
 'Korea, Rep.': array([648610576582.722, 602460189255.229, 26386409320.7449,
        1751045752054.63, 46150387327.4939], dtype=object),
 'Kosovo': array([2315620151.32626, 4458677258.30755, 571836195.627315,
        7899741278.75198, -2143057106.98129], dtype=object),
 'Kuwait': array([73327382736.4621, 55817806337.715, 521780172.655141,
        140856394860.529, 17509576398.7471], dtype=object),
 'Kyrgyz Republic': array([3137172120.63405, 5712149571.70613, 972166970.636164,
        9371275264.36735, -2574977451.07208], dtype=object),
 'Latvia': array([20699384824.9176, 20771523762.3294, 1275467685.37255,
        33099503950.847, -72138937.4117646], dtype=object),
 'Lebanon': array([10681277028.314, 21820628748.3913, 1635444374.19562,
        51605959131.2741, -11139351720.0772], dtype=object),
 'Lesotho': array([1104727469.64081, 2254606913.26468, 106716219.004325,
        2390702295.82777, -1149879443.62386], dtype=object),
 'Libya': array([29332965257.6089, 25373910344.4774, 1414188031.86525,
        69254496471.6938, 3959054913.13151], dtype=object),
 'Lithuania': array([42344067359.6078, 39443296204.549, 1722039501.02745,
        55122066225.796, 2900771155.05882], dtype=object),
 'Luxembourg': array([144341752039.059, 123031122937.043, 150104739.647059,
        69872035113.6469, 21310629102.0157], dtype=object),
 'Madagascar': array([4009166482.22619, 4820540217.6801, 3237902368.77263,
        14104664678.5063, -811373735.453912], dtype=object),
 'Malawi': array([1435575611.01415, 3448840700.9341, 2536112758.64028,
        11051852712.6142, -2013265089.91995], dtype=object),
 'Malaysia': array([238379861290.486, 210893037728.698, 26443665494.2583,
        365177721021.516, 27486823561.788], dtype=object),
 'Maldives': array([3751360417.55704, 4100560296.22075, 257332068.506919,
        5726094799.37709, -349199878.663704], dtype=object),
 'Mali': array([4449175629.33742, 6608368701.20412, 6607699657.62702,
        20477421884.5414, -2159193071.8667], dtype=object),
 'Malta': array([20343827022.3294, 17734740558.1792, 77099789.2045873,
        16337793530.7322, 2609086464.15016], dtype=object),
 'Marshall Islands': array([86317100.0, 270037900.0, 42409100.0, 232900000.0, -183720800.0],
       dtype=object),
 'Mauritania': array([3347184840.42049, 4033369861.07674, 1575627895.93793,
        7894764885.82312, -686185020.65625], dtype=object),
 'Mauritius': array([8837804269.59075, 9899441321.25382, 390826768.036561,
        14645235204.6176, -1061637051.66308], dtype=object),
 'Mexico': array([502467566320.434, 507718819549.77, 43231438885.3857,
        1304106203902.45, -5251253229.33634], dtype=object),
 'Micronesia, Fed. Sts.': array([105000000.0, 272000000.0, 91622700.0, 394000000.0, -167000000.0],
       dtype=object),
 'Moldova': array([3660834340.67571, 6624383483.98942, 1192553957.33193,
        11736797054.6965, -2963549143.31371], dtype=object),
 'Mongolia': array([8412612745.88232, 9259602726.47506, 1642025365.8847,
        14206359017.5143, -846989980.592748], dtype=object),
 'Montenegro': array([2430487406.2465, 3602221314.22814, 203081159.744767,
        5483476883.4658, -1171733907.98164], dtype=object),
 'Morocco': array([43952860516.0238, 54024112942.437, 13978053204.5291,
        128920266409.458, -10071252426.4132], dtype=object),
 'Mozambique': array([5761757708.23501, 10618346285.9034, 3842476569.27963,
        15512759046.672, -4856588577.66841], dtype=object),
 'Namibia': array([4565372504.91404, 5832030383.98715, 888467283.574652,
        12541928303.48, -1266657879.07312], dtype=object),
 'Nepal': array([2659663141.44733, 14176869011.1514, 7378530812.52977,
        34186180699.0255, -11517205869.704], dtype=object),
 'Netherlands': array([792548771333.332, 699981663066.666, 16337610996.0784,
        928903005576.469, 92567108266.6665], dtype=object),
 'New Caledonia': array([1736827318.1717, 3778986431.36819, 169248338.669003,
        9475655324.59495, -2042159113.1965], dtype=object),
 'New Zealand': array([58214279832.002, 57776826154.9864, 12118916248.0441,
        213006341101.869, 437453677.015565], dtype=object),
 'Nicaragua': array([5689725118.64939, 6252718088.9775, 1972130945.99937,
        12699023614.245, -562992970.328103], dtype=object),
 'Niger': array([1386835865.63682, 3395520048.36612, 4768094132.23984,
        12889555561.2299, -2008684182.7293], dtype=object),
 'North Macedonia': array([7867370857.84171, 9602017937.21973, 1025184176.80974,
        12606338448.547, -1734647079.37802], dtype=object),
 'Norway': array([149767159090.909, 140014431818.182, 7285681818.18182,
        408742840909.091, 9752727272.72727], dtype=object),
 'Oman': array([43583875162.5488, 32569570871.2614, 1756566970.09103,
        88060858257.4772, 11014304291.2874], dtype=object),
 'Pakistan': array([30136170670.3429, 62624564039.0062, 66357247840.5539,
        320909472770.669, -32488393368.6633], dtype=object),
 'Palau': array([108052230.834961, 217598205.566406, 9558255.859375,
        282041290.283203, -109545974.731445], dtype=object),
 'Panama': array([28061045272.5593, 28061255725.4778, 1713130594.12347,
        69778991192.5571, -210452.918498993], dtype=object),
 'Paraguay': array([13686227184.127, 13325018618.9235, 3666422095.01322,
        37925338329.156, 361208565.203489], dtype=object),
 'Peru': array([54892296037.3345, 52301323565.5929, 15648622658.0932,
        228346006003.648, 2590972471.74159], dtype=object),
 'Philippines': array([106953484846.44, 152458687320.163, 33237044033.1021,
        376823402239.136, -45505202473.7226], dtype=object),
 'Poland': array([317089370014.651, 295123034348.038, 14285398013.9997,
        602683770144.88, 21966335666.6124], dtype=object),
 'Portugal': array([104818126821.584, 103532874928.996, 4802123605.16862,
        240115970063.019, 1285251892.58823], dtype=object),
 'Puerto Rico (US)': array([63684400000.0, 49401600000.0, 717300000.0, 105126400000.0,
        14282800000.0], dtype=object),
 'Qatar': array([92046153846.1538, 66769780219.7802, 458516483.516483,
        176371428571.429, 25276373626.3736], dtype=object),
 'Romania': array([100870449571.429, 111463746998.826, 10782163440.8348,
        250080428511.595, -10593297427.3967], dtype=object),
 'Russian Federation': array([481410680627.341, 352088733268.664, 59772088276.6565,
        1693115002708.32, 129321947358.676], dtype=object),
 'Rwanda': array([2258780688.5869, 3741294748.63065, 2438360273.39147,
        10349300276.7623, -1482514060.04375], dtype=object),
 'Samoa': array([319836966.763327, 440934535.107256, 83120020.2598718,
        912950466.064906, -121097568.34393], dtype=object),
 'San Marino': array([2650754110.84242, 2315691530.34182, 246936.060258661,
        1616340692.28937, 335062580.500596], dtype=object),
 'Saudi Arabia': array([285860000000.0, 218974666666.667, 21812000000.0, 888890133333.333,
        66885333333.3333], dtype=object),
 'Senegal': array([5847051726.26615, 9186797791.08368, 3486322930.74853,
        23403995992.1354, -3339746064.81753], dtype=object),
 'Serbia': array([26372690325.2173, 31573497914.357, 2566517191.45462,
        53864693664.5568, -5200807589.13971], dtype=object),
 'Seychelles': array([1538983435.76862, 1701471825.8422, 39794773.1281065,
        1868690096.73454, -162488390.073575], dtype=object),
 'Sierra Leone': array([632404802.551566, 1817978349.30619, 2253712158.29391,
        6523577594.29408, -1185573546.75463], dtype=object),
 'Singapore': array([665397849809.186, 554852810304.965, 121320257.624117,
        376161998830.048, 110545039504.222], dtype=object),
 'Slovak Republic': array([97210994149.8744, 97247442000.9646, 1711499648.51764,
        105843498304.094, -36447851.090196], dtype=object),
 'Slovenia': array([45476824978.3842, 40802920386.196, 954424785.450979,
        53909922735.545, 4673904592.18823], dtype=object),
 'Solomon Islands': array([590941418.619108, 752930329.230226, 529000602.721657,
        1619150563.92084, -161988910.611118], dtype=object),
 'South Africa': array([105906059178.622, 103935027605.427, 7593185943.35563,
        389330032224.269, 1971031573.19478], dtype=object),
 'Spain': array([486670273121.568, 444777298015.686, 35365319239.2156,
        1403496387686.27, 41892975105.8823], dtype=object),
 'Sri Lanka': array([19422660191.249, 24565416647.1167, 6457965688.71717,
        88998706296.5783, -5142756455.86767], dtype=object),
 'Sudan': array([2733532469.42149, 5713051071.07438, 6520655246.28099,